[phases.setup]
nixPkgs = [
  "python311",
  "gcc",
  "pkg-config",
  "zlib",
  "libjpeg",
  "freetype",
  "libpng",
  "libtiff",
  "lcms2",
  "openjpeg",
  "fontconfig"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "bash -c 'python manage.py migrate && gunicorn core.wsgi:application'"
